// Copyright 2026 huija
//
// SPDX-License-Identifier: MIT

// cataloggen extracts i18n msgids from Go source, merges existing Chinese
// translations, and writes deterministic gettext PO catalogs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/huija/skillmod/internal/i18n/pofile"
)

type message struct {
	id          string
	translation string
}

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "check catalogs without writing them")
	flag.Parse()

	if err := run(filepath.Clean(*root), *check); err != nil {
		fmt.Fprintln(os.Stderr, "cataloggen:", err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	enPath := filepath.Join(root, "locales", "en_US.po")
	zhPath := filepath.Join(root, "locales", "zh_CN.po")
	existing, err := readExisting(zhPath)
	if err != nil {
		return err
	}
	messages, err := scan(root, existing)
	if err != nil {
		return err
	}

	en := render(messages, "en_US")
	zh := render(messages, "zh_CN")
	if check {
		if err := equalFile(enPath, en); err != nil {
			return err
		}
		if err := equalFile(zhPath, zh); err != nil {
			return err
		}
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(zhPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(enPath, en, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(zhPath, zh, 0o644); err != nil {
		return err
	}

	var missing []string
	for _, msg := range messages {
		if msg.translation == "" {
			missing = append(missing, msg.id)
		}
	}
	if len(missing) != 0 {
		return fmt.Errorf("%d messages need zh_CN translations (first: %q)", len(missing), missing[0])
	}
	return nil
}

func readExisting(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]string{}, nil
	}
	if err != nil {
		return nil, err
	}
	return pofile.Parse(data)
}

func scan(root string, existing map[string]string) (map[string]*message, error) {
	messages := map[string]*message{}
	fset := token.NewFileSet()
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "locales" {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".go" || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		var inspectErr error
		ast.Inspect(file, func(n ast.Node) bool {
			if inspectErr != nil {
				return false
			}
			call, ok := n.(*ast.CallExpr)
			if !ok || len(call.Args) == 0 || !isI18nCall(call.Fun) {
				return true
			}
			msgid, ok := literal(call.Args[0])
			if !ok {
				pos := fset.Position(call.Pos())
				inspectErr = fmt.Errorf("%s:%d: i18n msgid must be a string literal", path, pos.Line)
				return false
			}
			msg := messages[msgid]
			if msg == nil {
				msg = &message{id: msgid, translation: existing[msgid]}
				messages[msgid] = msg
			}

			return true
		})
		return inspectErr
	})
	return messages, err
}

func isI18nCall(expr ast.Expr) bool {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok || (sel.Sel.Name != "Text" && sel.Sel.Name != "Format") {
		return false
	}
	id, ok := sel.X.(*ast.Ident)
	return ok && id.Name == "i18n"
}

func literal(expr ast.Expr) (string, bool) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	value, err := strconv.Unquote(lit.Value)
	return value, err == nil
}

func render(messages map[string]*message, language string) []byte {
	var out bytes.Buffer
	out.WriteString("# Generated by go generate ./internal/i18n.\n")
	if language == "zh_CN" {
		out.WriteString("# Simplified Chinese translations for skillmod.\n")
	} else {
		out.WriteString("# English translations for skillmod.\n")
	}
	out.WriteString("msgid \"\"\nmsgstr \"\"\n")
	out.WriteString("\"Project-Id-Version: skillmod\\n\"\n")
	if language == "zh_CN" {
		out.WriteString("\"PO-Revision-Date: 2026-09-02 00:00+0800\\n\"\n")
		out.WriteString("\"Last-Translator: skillmod contributors\\n\"\n")
		out.WriteString("\"Language-Team: Simplified Chinese\\n\"\n")
		out.WriteString("\"Language: zh_CN\\n\"\n")
	} else {
		out.WriteString("\"PO-Revision-Date: 2026-09-02 00:00+0800\\n\"\n")
		out.WriteString("\"Last-Translator: skillmod contributors\\n\"\n")
		out.WriteString("\"Language-Team: English (United States)\\n\"\n")
		out.WriteString("\"Language: en_US\\n\"\n")
	}
	out.WriteString("\"MIME-Version: 1.0\\n\"\n")
	out.WriteString("\"Content-Type: text/plain; charset=UTF-8\\n\"\n")
	out.WriteString("\"Content-Transfer-Encoding: 8bit\\n\"\n\n")

	ids := make([]string, 0, len(messages))
	for id := range messages {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		msg := messages[id]
		if strings.Contains(id, "%") {
			out.WriteString("#, go-format\n")
		}
		out.WriteString("msgid " + strconv.Quote(id) + "\n")
		value := id
		if language == "zh_CN" {
			value = msg.translation
		}
		out.WriteString("msgstr " + strconv.Quote(value) + "\n\n")
	}
	return out.Bytes()
}

func equalFile(path string, want []byte) error {
	got, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("%s is stale; run go generate ./internal/i18n", path)
	}
	return nil
}
